### ISSUE TITLE
music bug

### ISSUE THREAD

**Issue by croot** [Juribiyan/instant-0chan#1]
Мужик, есть жирная бага, крепишь к посту mp3/ogg, всё залилось играется, но. Нельзя c плеером взаимодействовать, открывается еще один плеер, куда по плееру не ткни результат один. Такие дела.

**Comment by Juribiyan** [comment]
https://github.com/Juribiyan/instant-0chan/commit/d8ac524f7abb905b715d0f0a8ebc6e534ba3314d
